name: Continuous Integration
on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches: [develop]
  workflow_dispatch:
  workflow_call:
    
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  version:
    name: Prepare version string
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Output version string
        id: version
        run: echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
  package:
    needs: [build, version]
    name: Package
    uses: ./.github/workflows/package.yml
    with:
      version: ${{ needs.version.outputs.version }}
